depot/config/routes.rb
Depot::Application.routes.draw do

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match "/signup" => "users#new"

  resources :comments
  
  resources :users
  
  resources :orders

  resources :line_items

  resources :carts
  resources :products

  get "store/index"
  resources :products do
    get :who_bought, :on => :member
  end

  resources :products do
    resources :comments
  end

  root :to => 'store#index', :as => 'store'

end

depot/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag  "scaffold" %>
  <%= stylesheet_link_tag  "depot", :media => "all"  %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>

<body id="store" >

   <div id="banner" >
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
    
   </div>
<div id="log_status">
    <% if session[:user_id] %>
    <p> <%= link_to "Welcome! #{User.find(session[:user_id]).name}", :controller => 'users', :action => 'show', :id => session[:user_id] %></p>
    <%= button_to 'Logout', logout_path, :method => :delete   %>
    <% else %>
      <%= link_to 'Login', login_path, :method => :new %>
    <% end %>
  </div>
<div id="columns" >

<div id="side" >
<div id="cart" >

<% if @cart %>
<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
<%= render @cart %>
<% end %>
<% end %>
</div>

<a href="http://0.0.0.0:3000/" >Home</a><br />
<a href="http://www..../faq" >Questions</a><br />
<a href="http://www..../news" >News</a><br />
<a href="http://www..../contact" >Contact</a><br /><br />
<% if session[:user_id] %>
    <br />
    <%= link_to 'Orders',   orders_path   %><br />
    <%= link_to 'Products', products_path %><br />
    <%= link_to 'Users',    users_path    %><br />
    <br />
<% end %>

</div>

<div id="main" >
<%= yield %>
</div>

</div>


</body>

</html>